[phases.setup]
nixPkgs = [
  "gobject-introspection",
  "pango",
  "glib",
  "cairo",
  "libffi",
  "fontconfig",
  "freetype",
  "harfbuzz",
  "gdk-pixbuf",
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python app.py"